#+TITLE: dagerman2010: Ormen
#+ROAM_KEY: cite:dagerman2010

- tags ::
- keywords ::


* dagerman2010: Ormen
  :PROPERTIES:
  :Custom_ID: dagerman2010
  :URL:
  :AUTHOR: Dagerman, S.
  :NOTER_DOCUMENT:
  :NOTER_PAGE:
  :END:

* Anteckningar om Dagerman, S. (2010) - Ormen
  :PROPERTIES:
  :CUSTOM_ID: anteckningar-om-dagerman-s.-2010---ormen
  :END:

Tänker idag den 10 april 2021 att jag ska börja ta mig an Dagermans
författarskap på allvar och läsa alla hans böcker i den ordning de utkom
och att också försöka på allvar att göra gedigna läsningar av dem där
jag flitigt antecknar mina reflektioner och försöker att på allvar
skriva den slags kritik som jag uppskattar att läsa av andra.

Så här tänker jag mig läsordningen:

- [[https://archive.fo/Gct1C][*Ormen*]] (1945)
- [[https://archive.fo/GWpXX][De dömdas ö]] (1946)
- [[https://archive.fo/B8yjn][Tysk höst]] (1947)
- [[https://archive.fo/kQvZz][Nattens lekar]] (1947)
- [[https://archive.fo/KjA8c][Dramer om dömda]] (1948)
- [[https://archive.fo/zrL9h][Bränt barn]] (1948)
- [[https://archive.fo/Z5Z6e][Judasdramer]](1949)
- [[https://archive.fo/EkAFi][Bröllopsbesvär]] (1949)
- [[https://archive.fo/hVXCy][Blekplatsen]] (Översättning av Vesaas
  roman) (1950)
- [[https://archive.fo/NZvmN][Den yttersta dagen]] (1952)
- [[https://archive.fo/qaxnz][Dagsedlar]] (1954)
- [[https://archive.fo/2jNVf][Tusen år hos Gud]] (1954)

"Det var så varmt att man nästan kunde ha rostat kaffe på
järnvägsrälsen." är den oförglömliga mening som inleder Dagermans
författarskap. Jag kommer att tänka på hur Duras påbörjar sin debut
[citep:duras2011, s.3]: "Maud ouvrit la fenêtre et la rumeur de la vallée
emplit la chambre."

I Dagermans fall är det hettan som känns inpå bara kroppen som är den
ton som slås an, medan det i Duras fall är ljudet från omvärlden som ger
sig tillkänna. Men det är inte bara hettan som är påtaglig i Dagermans
roman utan rädslan finns där hela tiden som en slag nerv som förbinder
karaktärerna. Stundtals övergår den i verkligt hotfulla situationer som
under korta sekvenser inger panik hos karaktärerna men strax därefter
lyckas de komma något sånär till sans. Men oron och rädslan släpper
aldrig helt sitt greppet om dem utan finns där latent.

Den orm som också bokstavligen stängs in i en säck blir här också en
metafor, ett uttryck eller en symbol för något som man anar är ännu
värre.. men vad, vad bottnar all denna rädsla i och är den befogad?

Vad är personerna rädda för egentligen? Jag anar att det är den
själsliga ensamheten och den rädsla eller kanske snarare skräck som
ligger i att när allt kommer omkring är vi helt ensamma och utsatta.
Dagerman fångar denna själsliga rädsla på ett häpnadsväckande sätt:

#+begin_quote
  Hon låter sig långsamt sjunka ner i höet som är så torrt att det
  nästan bryts som torra kvistar. Hon ligger på rygg och ser med kisande
  ögon sommarmolnen rulla fram på himlen. Mellan molnen är himlen så
  obarmhärtigt blå och djupet så oändligt att det svindlar för henne och
  hon får en befriande känsla av att hon skulle kunna försvinna där utan
  att det gjorde ont. Vad är det som har hänt? tänker hon då upp mot det
  blå men där finns ingenting som kan svara. Där finns bara tomhet. Då
  sluter hon lugnad ögonen och vet att om hon låter sej uppslukas av den
  skall ingenting kunna hända henne. Men innerst inne vet hon ju att
  detta hopp är bedrägligt. Det är den fege lindansarens som tror sej
  frälst från höjden bara för att han blundar. För inne i henne gnager
  ett djur med // spetsiga tänder och hon har det instängt i en liten
  ask men redan kan hon skymta huggtanden genom det bräckliga höljet. Då
  stoppar hon skyndsamt den lilla asken i en något större men det lilla
  djuret gnager och gnager och nu hämtar hon en liten kartong och sedan
  en större och så ytterligare en större och varje gång känner hon samma
  barnsliga glädje och samma förnimmelse av avgrund när skräcken snuddar
  vid henne. citep:dagerman2010 s. 75-76
#+end_quote

Debutboken kom alltså ut när han var tjugotvå år. Det är helt ofattbart
vilken mognad som författare och människa han uppvisar redan då. Citatet
ovan är ju en form av gnagande grundkänsla som alla människor bär på,
det ofattbara livets gåta. Absurditeten i att vi faktiskt lever och det
ofattbara i att vi ska dö, och den ångest som det framkallar när vi på
djupet försöker göra det begripligt för oss.

De inre demonerna liknas alltså vid ett djur som man försöker stänga in
men som återkommande gör sig påmint. Irène träffar på en
slaktarbudspojke som ingående beskriver slaktarmasken, "en sån där
pickadolver som man knäpper grisar, ja oxar å kor me förresten me"
[@dagerman2010, s. 80]. Sin pojkvaskerhet till trots så förmår ändå
pojken att döda djuret, och därmed stänga det ute och inte låta det
gnaga på ens existens. Hans sällskap håller hennes inre djur stången:

#+begin_quote
  Måtte han nu bara fortsätta att prata, tänker hon ivrigt och andfått,
  så jag inte blir ensam, och djuret är så instängt inom bastanta väggar
  att hon knappast ens kan höra det ihåligt ekande nafset av tänderna.
  citep:dagerman2010, s.80
#+end_quote

Irène oroar sig för att bli ensam igen och för att det inre djuret då
ska göra sig påmint:

#+begin_quote
  Hon tänker be honom gå med in därför att det är logiskt när han gjort
  sej så stort besvär och dels också för djurets skull som kräver allt
  större lådor.  citep:dagerman, s. 86]
#+end_quote

Att djuret kräver allt större lådor, hur ska det tolkas? Jo, det är väl
bara en logisk fortsättning på den metafor som påbörjats redan tidigare,
men tolkningen blir ju också den att det krävs allt starkare medel för
att hålla demonerna borta när man väl har börjat att stänga in dem.

Romanen kännetecknas på ett generellt plan av många metaforer som inte
bara är av det allvarstyngda hållet utan stundtals riktigt lustiga, som
här:

#+begin_quote
  Huset ser ut som någonting som från början varit tänkt som en villa
  men sedan på grund av missuppfattning av byggmästarn eller brist på
  pengar eller intresse stannat i växten. Det är byggt i ett plan och
  har på gaveln en pampig glasveranda som passar till huset i övrigt som
  en stormhatt på en terrier.  citep:dagerman, s. 86
#+end_quote
