#+TITLE: sandell2021: Passerande
#+ROAM_KEY: cite:sandell2021

- tags ::
- keywords ::


* sandell2021: Passerande
  :PROPERTIES:
  :Custom_ID: sandell2021
  :URL:
  :AUTHOR: Sandell, H.
  :NOTER_DOCUMENT:
  :NOTER_PAGE:
  :END:


Håkan Sandells nya diktsamling heter Passerande och är en av hans mest lättillgängliga på senare år. Titeln är passande för boken uppehåller sig just vid passeranden av olik slag. Bilden av en kvinna som föder över en grav passar väl in här för vad är livet om inte blott ett kort passerande, en liten strimma ljus innan allt blir mörker igen. Den position berättarrösten är en röst som inte enbart utgör från honom själv utan som liksom står utanför och ser in på skeendena utifrån, som en ande eller en vind med ett registrerande medvetande. Kanske kommer i någon mån alltid poetens röst därifrån, men här är det extra tydligt. Det är en röst som vill fånga och få oss att uppmärksamma och med försoning och ödmjukhet betrakta dessa korta ögonblick som passerar i våra liv, i våra samhällen. Genom träffande metaforer som blandar det samtidiga, av människan skapade, med det eviga blir vi varse vilken tidsålder vi har att göra med. Vad är konst och vad är poesi? Jo, att "make things the object of attention":

[[file:../202002052228 Art makes things the object of attention.org][202002052228 Art makes things the object of attention]]

Apropå poeten som en vind med ett medvetande som registrerar, kan också nämnas hur Bodegård ser på Milosz cite:milosz2000 sidan 111:

"Många vill fånga Czeslaw Milosz i ett ord, inte minst nu när han är borta. [...] Själv har jag betecknat honom som "en flod som far fram i en osedvanlig fåra genom tid och rum". Nu vill jag byta element och tänker på honom som "vägar", "stigar" över jorden. Och samtidigt tycks han i _DET_ också vara på andra sidan. Han lever inte längre på jorden, men med sina dikter komponerar han en bestående närvaro."

[[file:../201911032208 - Czeslaw Milosz om drömmens kraft och lycka.org][201911032208 - Czeslaw Milosz om drömmens kraft och lycka]]
